### ISSUE TITLE
When no results are returned, the loader graphic remains...

### ISSUE THREAD

**Issue by epugh** [fredwu/jquery-endless-scroll#1]
Because the div#endless_scroll_loader remove call: $("div#endless_scroll_loader").remove(); is in if (data !== false), when I get no results back then it just stays there....  

I had to explicitly add this:

```
if (response.response.docs.length == 0){
        no_more_results = true;
        $("div#endless_scroll_loader").remove();
      }
```

**Comment by fredwu** [comment]
Thanks for the report. This should be fixed in v1.4.4. :)
