### ISSUE TITLE
loader options doesn't work

### ISSUE THREAD

**Issue by JeroenVdb** [fredwu/jquery-endless-scroll#11]
If I add a loader to my code it never shows up. I'm loading data from an ajax call (via callback). 
If I add the loader to your example it also doesn't work...

``` javascript
loader: "<li style='width:600px; height:200px; background-color:red'>LOADING !!!</li>",
```

**Comment by joshangell** [comment]
Yeah I'm having the same issue...any luck yet anyone?

**Comment by mgartner** [comment]
I'm having the same problem as well.

**Comment by yablokoff** [comment]
ths same unfortunately

**Comment by abraham** [comment]
Looks like it is getting added to the DOM but it does't appear to be visible. Each scroll is also leaving `<div style="display: block; "></div>` where the loading message was. After a few scrolls there are a bunch of them.

**Comment by fredwu** [comment]
Fixed and updated the demo to include the loader. :)
