### ISSUE TITLE
Request ceaseFire example

### ISSUE THREAD

**Issue by JeroenVdb** [fredwu/jquery-endless-scroll#12]
Hi Fred

Is there a possibility to update the manual with an example for the ceaseFire option? I can't get it to work.
It would also be nice if we could get the 'times fired' in the ceaseFire function.

This is what I have, it doens't work, also no error...

``` javascript
$(function() {
      $('ul#list').endlessScroll({
        fireOnce: false,
    fireDelay: false,
        insertAfter: "ul#list div:last",
    callback: function() {
        //ajax call
    },
        ceaseFire: function(i) { if(i==10) { return true; } }
      });
    });
```

**Comment by fredwu** [comment]
Fixed. :)
