### ISSUE TITLE
How to cancel the endless scroll ?

### ISSUE THREAD

**Issue by alokmandloi** [fredwu/jquery-endless-scroll#13]
I know it can be cancelled using the ceasfire function but i want to cancel the endless scroll and attach another endless scroll.

**Comment by thepixelmonk** [comment]
return false in the data callback?

**Comment by afeld** [comment]
Would be nice to have a method, though...

**Comment by fredwu** [comment]
You can attach another instance of EndlessScroll in the ceaseFire function. :)

**Comment by JackieManuja** [comment]
when I add another instance of EndlessScroll scroll the 1st instance remains there. how can I completely remove first instance.
