### ISSUE TITLE
efficiency

### ISSUE THREAD

**Issue by afeld** [fredwu/jquery-endless-scroll#15]
Really nice plugin, thanks!  Was just referred to a post by John Resig about how to reduce the weight of the `scroll()` callback - might be interesting to consider how that would change the implementation.

http://ejohn.org/blog/learning-from-twitter/

Maybe I'll take a stab at it one of these days...

**Comment by fredwu** [comment]
Thanks, implemented! :)

**Comment by afeld** [comment]
4 hr. turnaround time for a big change like this?  Rock on, sir.
