### ISSUE TITLE
customizing loader

### ISSUE THREAD

**Issue by alokmandloi** [fredwu/jquery-endless-scroll#19]
Custom Loader Styles

You may customise the look and feel of the loader by changing:

The endless_scroll_loader class;
Or the endless_scroll_loader_<scroller_dom_html_id>.

the above is mentioned in the documentation . I do not understand how do i use as written above to customize the loader .. 
It would be great if an example could be provided

**Comment by fredwu** [comment]
In the [demo page](http://fredwu.github.com/jquery-endless-scroll/) you can see how I have customised the loader. :)

**Comment by alokmandloi** [comment]
thanks .. done with it
