### ISSUE TITLE
Can't get it to work with jQuery >= 1.5x when ussed on a different from $(document) element

### ISSUE THREAD

**Issue by dpetrov** [fredwu/jquery-endless-scroll#2]
I am not quite sure if it's just me, but the Plugin seems not to work with jQuery version which is higher than 1.5x. Can anyone confirm?

**Comment by fredwu** [comment]
I just tested the demo with 1.6.1 and it works fine. Could you please provide more information? Any errors in the console?

**Comment by dpetrov** [comment]
Thanks a lot for the imediate response. I was reading the changelog and since v1.4 [2010-06-18] it seems to work on any element right? So if I used it on $(document) it seems to work without anyproblem. However if I try to use some element, like: $('#list').endlessScroll the endless scroll is not triggered. Or may be i've just misinterpreted how should I use it?

**Comment by fredwu** [comment]
Updated with a DOM-based demo. Please check the demo files to see how to use the script. :)

Please feel free to re-open this issue if there's still problems. Thanks!

**Comment by dpetrov** [comment]
Thanks a lot
