### ISSUE TITLE
Removing endless scroll

### ISSUE THREAD

**Issue by axsuul** [fredwu/jquery-endless-scroll#22]
I would like to remove endless scroll from `$(window)` at a certain point, is there any way to do that?

**Comment by axsuul** [comment]
Nevermind, I figured out a solution with the `ceaseFire` callback

**Comment by JackieManuja** [comment]
Hi  Axsuul,

I would like to remove endless scroll from $(document) at certain point & attach once again(re-attach with new values) how it can be done.

Thanks in advance
