### ISSUE TITLE
How to disable up scroll?

### ISSUE THREAD

**Issue by coolgefyt-zz** [fredwu/jquery-endless-scroll#23]
Is it possible to disable up scroll, only down scroll work?

**Comment by fredwu** [comment]
If you don't set `pagesToKeep`, then there will be no content being discarded therefore no infinite up-scrolling.

**Comment by jgarbers** [comment]
I'm using the callback to append AJAX-fetched content to the end of my endlessly-scrolling table, and ceaseFireOnEmpty is set to false. I don't have pagesToKeep set, but upward scroll events are still firing whenever I try to scroll back up to the top of my table. "Loading..." appears at the top, disappears, and I can't get back up to the top few rows.  Any suggestions?
