### ISSUE TITLE
data truncation does not work (jquery 1.7.2 / jquery-endless-scroll 1.8.0)

### ISSUE THREAD

**Issue by Levure** [fredwu/jquery-endless-scroll#28]
Hello !

I have an issue with jquery-endless-scroll data truncation.

Here's a cleaned sample page with the issue : http://www.capharnaum.be/debug-jquery-endless-scroll/

What I would like to get : When the visitor loads the page, all items which are below the browser bottom are hidden (so, data truncation). When the visitor scroll to the bottom, an item is then displayed, and so on until the end of items...
Note there isn't any data to load from an external source, all the items are already on the page.

But, currently : everything is displayed immediately. It's seems that the jquery-endless-scroll does anything.

Am I missing something ?

Many thanks in advance for your help !

Kind regards,

**Comment by fredwu** [comment]
Hi, in this case you would want to hide the extra items yourself, and then tell endless scroll to unhide them upon scrolling.

**Comment by Levure** [comment]
Thanks for your (quick!) reply, fredwu. I'm going to give a try !

IMHO, the documentation and the demo page should be more complete. If I provide a sample (for other developpers), will you add it in the demo page ?

**Comment by fredwu** [comment]
Sure, if the example is very different than the existing ones then yes! :)
