### ISSUE TITLE
Not working on Internet Explorer 7 + 8

### ISSUE THREAD

**Issue by stijink** [fredwu/jquery-endless-scroll#7]
Hi Fred,

first of all thank you for this great plugin. Works fine for me. When testing my ongoing developement i noticed that the plugin is not working with Internet Explorer 7 + 8. Maybe you have an idea about this issue.

For my development these browsers are still "mission critial", since a lot of users are still using them.

**Comment by christianhaller** [comment]
for IE6/IE7

use $(window).endlessScroll() 

instead of $(document).endlessScroll()

**Comment by stijink** [comment]
Thanks. Bugfix provided.
